New commands for tags
arduinodiscord/bot-legacy pull request #105
Opened 2021-06-14 06:54 UTC by Prakul2006

ill eventually add tags for all the commands in arduino reference

2021-06-15 05:25 UTC, BluLightShow requested changes
We're currently not interested in hand-translating all of the Arduino reference pages into bot tags. Instead, the helpers believe a simple quick hyperlink to the reference pages would suffice. Turning these reference tags into quick links is the way to go :)

2021-06-15 05:25 UTC, BluLightShow commented on commands/tag.js
> +              .setFooter(field.footer)
Right now we want to stick with a universal footer for all tags.

2021-06-15 05:27 UTC, Prakul2006 commented on commands/tag.js
> +              .setFooter(field.footer)
ok 👍

2021-09-05 08:28 UTC, BluLightShow commented
If this is still applicable, please open a new pull request off of the latest develop. Thanks for contributing.

2021-09-05 08:28 UTC, closed without merging