Feature/new helper tags
arduinodiscord/bot-legacy pull request #130
Opened 2022-02-10 13:42 UTC by ZanzyTHEbar

###  I have created custom nodms and solder json files to teach people: 

1. How to properly solder - with examples.

2. Not to dm people without their consent.

2022-02-15 00:16 UTC, ZanzyTHEbar commented
no reviews yet - How active is this?

2022-02-15 00:22 UTC, hox commented
Hi! We're discussing this internally and will review this when we can.

2022-02-15 19:26 UTC, ZanzyTHEbar commented
eh! A response - cool. All i needed ;) Thanks, wasn't sure if this github was still being actively maintained.

2022-02-17 05:50 UTC, BluLightShow requested changes
Please read individual file comments.
TRLDR; Please remove settings.json, nodms.json, wokwi.json + edit solder.json

Thank you for your contribution! If you have any questions feel free to ask. Once these changes are made I will merge this request.

2022-02-17 05:50 UTC, BluLightShow commented on .vscode/settings.json
> +{
VSCode configuration files are not necessary. This file can be removed.

2022-02-17 05:50 UTC, BluLightShow commented on src/tags/nodms.json
> +{
After discussing this tag internally we have determined we will not be adding tags that repost rules available in our code of conduct channel. This file can be removed.

2022-02-17 05:50 UTC, BluLightShow commented on src/tags/solder.json
> +{
We would like to add this soldering tag! However, the button and its reply are not needed.

2022-02-17 05:50 UTC, BluLightShow commented on src/tags/wokwi.json
> +{
As of now, we will not be linking to particular third-party sites through tags in this way. This file can be removed.

2022-02-17 10:24 UTC, ZanzyTHEbar commented on .vscode/settings.json
> +{
Yeah - this makes sense. Didn't really mean to upload it anyhow - just something i use for my personal development. Changes have been made.

2022-02-17 10:26 UTC, ZanzyTHEbar commented on src/tags/nodms.json
> +{
Dang, I understand, but it's sad. I am so tired of having to tell people this and link them to the #welcome channel - they nevecr read it and people even argue with me that since it's not in rules they don't have to follow it - or say that i am being rude for telling them not to dm me - i really feel like this needs to be AT LEAST moved to the #code-of-conduct section. However, that's jsut a pesonal greivance - thank you for considering my changes.

2022-02-17 10:27 UTC, ZanzyTHEbar commented on src/tags/solder.json
> +{
Understood, i have resolved for the requested changes.

2022-02-17 23:15 UTC, BluLightShow approved these changes
Looks good, thanks for making those changes!

2022-02-17 23:16 UTC, merged