D band ohm
arduinodiscord/bot-legacy pull request #133
Opened 2022-03-07 21:31 UTC by Supperslash

Lets try this again.

2022-03-07 21:32 UTC, Supperslash commented
Added tags: Ohms lay, and De-bounce. Also corrected spelling error. Requested by helpers. :D

2022-03-12 02:47 UTC, BluLightShow requested changes
Please see specific comments.

2022-03-12 02:47 UTC, BluLightShow commented on src/tags/debounce.json
> +  "image": "http://wiki.ros.org/rosserial_arduino/Tutorials/Push%20Button?action=AttachFile&do=get&target=debounce.png"
There can only be one image associated with a tag. Please choose one to keep.

2022-03-12 03:35 UTC, Supperslash commented on src/tags/debounce.json
> +  "image": "http://wiki.ros.org/rosserial_arduino/Tutorials/Push%20Button?action=AttachFile&do=get&target=debounce.png"
The extra image should be removed.

2022-03-12 04:44 UTC, BluLightShow approved these changes
Looks good!

2022-03-12 04:45 UTC, merged

2022-03-12 04:45 UTC, BluLightShow commented
Thanks for your contribution!